// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFCsVm3-21OHEX4gZzVlaI1pF-zrmomA',
    appId: '1:1097050210984:web:7907d8fef9121ceac6789d',
    messagingSenderId: '1097050210984',
    projectId: 'signin-project-b5805',
    authDomain: 'signin-project-b5805.firebaseapp.com',
    storageBucket: 'signin-project-b5805.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzarqNIsxcBmm8Iy9Geec3PuSr8y6pEHA',
    appId: '1:1097050210984:android:083ad8a4172568cfc6789d',
    messagingSenderId: '1097050210984',
    projectId: 'signin-project-b5805',
    storageBucket: 'signin-project-b5805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3yKrkRi2gLsaekaOa1GqOwOzGtDYIF_U',
    appId: '1:1097050210984:ios:8279d1f90e6afb0bc6789d',
    messagingSenderId: '1097050210984',
    projectId: 'signin-project-b5805',
    storageBucket: 'signin-project-b5805.appspot.com',
    iosBundleId: 'com.example.catanddog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3yKrkRi2gLsaekaOa1GqOwOzGtDYIF_U',
    appId: '1:1097050210984:ios:d867ad9513ceba44c6789d',
    messagingSenderId: '1097050210984',
    projectId: 'signin-project-b5805',
    storageBucket: 'signin-project-b5805.appspot.com',
    iosBundleId: 'com.example.catanddog.RunnerTests',
  );
}
